routes/web.php
<?php

use App\Http\Middleware\ForceStripeAccount;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/concerts/{id}', 'ConcertsController@show')->name('concerts.show');
Route::post('/concerts/{id}/orders', 'ConcertOrdersController@store');
Route::get('/orders/{confirmationNumber}', 'OrdersController@show');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('auth.show-login');
Route::post('/login', 'Auth\LoginController@login')->name('auth.login');
Route::post('/logout', 'Auth\LoginController@logout')->name('auth.logout');

Route::post('/register', 'Auth\RegisterController@register')->name('auth.register');

Route::get('/invitations/{code}', 'InvitationsController@show')->name('invitations.show');

Route::group(['middleware' => 'auth', 'prefix' => 'backstage', 'namespace' => 'Backstage'], function () {
    Route::group(['middleware' => ForceStripeAccount::class], function () {
        Route::get('/concerts', 'ConcertsController@index')->name('backstage.concerts.index');
        Route::get('/concerts/new', 'ConcertsController@create')->name('backstage.concerts.new');
        Route::post('/concerts', 'ConcertsController@store')->name('backstage.concerts.store');
        Route::get('/concerts/{id}/edit', 'ConcertsController@edit')->name('backstage.concerts.edit');
        Route::patch('/concerts/{id}', 'ConcertsController@update')->name('backstage.concerts.update');

        Route::post('/published-concerts', 'PublishedConcertsController@store')->name('backstage.published-concerts.store');
        Route::get('/published-concerts/{id}/orders', 'PublishedConcertOrdersController@index')->name('backstage.published-concert-orders.index');

        Route::get('/concerts/{id}/messages/new', 'ConcertMessagesController@create')->name('backstage.concert-messages.new');
        Route::post('/concerts/{id}/messages', 'ConcertMessagesController@store')->name('backstage.concert-messages.store');
    });

    Route::get('/stripe-connect/connect', 'StripeConnectController@connect')->name('backstage.stripe-connect.connect');
    Route::get('/stripe-connect/authorize', 'StripeConnectController@authorizeRedirect')->name('backstage.stripe-connect.authorize');
    Route::get('/stripe-connect/redirect', 'StripeConnectController@redirect')->name('backstage.stripe-connect.redirect');
});

app/Concert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use App\Exceptions\NotEnoughTicketsException;

class Concert extends Model
{
    protected $guarded = [];
    protected $dates = ['date'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function attendeeMessages()
    {
        return $this->hasMany(AttendeeMessage::class);
    }

    public function scopePublished($query)
    {
        return $query->whereNotNull('published_at');
    }

    public function isPublished()
    {
        return $this->published_at !== null;
    }

    public function publish()
    {
        $this->update(['published_at' => $this->freshTimestamp()]);
        $this->addTickets($this->ticket_quantity);
    }

    public function getFormattedDateAttribute()
    {
        return $this->date->format('F j, Y');
    }

    public function getFormattedStartTimeAttribute()
    {
        return $this->date->format('g:ia');
    }

    public function getTicketPriceInDollarsAttribute()
    {
        return number_format($this->ticket_price / 100, 2);
    }

    public function orders()
    {
        return Order::whereIn('id', $this->tickets()->pluck('order_id'));
    }

    public function hasOrderFor($customerEmail)
    {
        return $this->orders()->where('email', $customerEmail)->count() > 0;
    }

    public function ordersFor($customerEmail)
    {
        return $this->orders()->where('email', $customerEmail)->get();
    }

    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function reserveTickets($quantity, $email)
    {
        $tickets = $this->findTickets($quantity)->each(function ($ticket) {
            $ticket->reserve();
        });

        return new Reservation($tickets, $email);
    }

    public function findTickets($quantity)
    {
        $tickets = $this->tickets()->available()->take($quantity)->get();

        if ($tickets->count() < $quantity) {
            throw new NotEnoughTicketsException;
        }

        return $tickets;
    }

    public function addTickets($quantity)
    {
        foreach (range(1, $quantity) as $i) {
            $this->tickets()->create([]);
        }

        return $this;
    }

    public function ticketsRemaining()
    {
        return $this->tickets()->available()->count();
    }

    public function ticketsSold()
    {
        return $this->tickets()->sold()->count();
    }

    public function totalTickets()
    {
        return $this->tickets()->count();
    }

    public function percentSoldOut()
    {
        return number_format(($this->ticketsSold() / $this->totalTickets()) * 100, 2);
    }

    public function revenueInDollars()
    {
        return $this->orders()->sum('amount') / 100;
    }

    public function hasPoster()
    {
        return $this->poster_image_path !== null;
    }

    public function posterUrl()
    {
        return Storage::disk('public')->url($this->poster_image_path);
    }
}

app/Http/Controllers/Backstage/ConcertMessagesController.php
<?php

namespace App\Http\Controllers\Backstage;

use Illuminate\Http\Request;
use App\Jobs\SendAttendeeMessage;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ConcertMessagesController extends Controller
{
    public function create($id)
    {
        $concert = Auth::user()->concerts()->findOrFail($id);

        return view('backstage.concert-messages.new', ['concert' => $concert]);
    }

    public function store($id)
    {
        $concert = Auth::user()->concerts()->findOrFail($id);

        $this->validate(request(), [
            'subject' => ['required'],
            'message' => ['required'],
        ]);

        $message = $concert->attendeeMessages()->create(request(['subject', 'message']));

        SendAttendeeMessage::dispatch($message);

        return redirect()->route('backstage.concert-messages.new', $concert)
            ->with('flash', "Your message has been sent.");
    }
}

app/Http/Controllers/Backstage/ConcertsController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Concert;
use App\NullFile;
use Carbon\Carbon;
use App\Events\ConcertAdded;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ConcertsController extends Controller
{
    public function index()
    {
        return view('backstage.concerts.index', [
            'publishedConcerts' => Auth::user()->concerts->filter->isPublished(),
            'unpublishedConcerts' => Auth::user()->concerts->reject->isPublished(),
        ]);
    }

    public function create()
    {
        return view('backstage.concerts.create');
    }

    public function store()
    {
        $this->validate(request(), [
            'title' => ['required'],
            'date' => ['required', 'date'],
            'time' => ['required', 'date_format:g:ia'],
            'venue' => ['required'],
            'venue_address' => ['required'],
            'city' => ['required'],
            'state' => ['required'],
            'zip' => ['required'],
            'ticket_price' => ['required', 'numeric', 'min:5'],
            'ticket_quantity' => ['required', 'numeric', 'min:1'],
            'poster_image' => ['nullable', 'image', Rule::dimensions()->minWidth(600)->ratio(8.5/11)],
        ]);

        $concert = Auth::user()->concerts()->create([
            'title' => request('title'),
            'subtitle' => request('subtitle'),
            'additional_information' => request('additional_information'),
            'date' => Carbon::parse(vsprintf('%s %s', [
                request('date'),
                request('time'),
            ])),
            'venue' => request('venue'),
            'venue_address' => request('venue_address'),
            'city' => request('city'),
            'state' => request('state'),
            'zip' => request('zip'),
            'ticket_price' => request('ticket_price') * 100,
            'ticket_quantity' => (int) request('ticket_quantity'),
            'poster_image_path' => request('poster_image', new NullFile)->store('posters', 'public'),
        ]);

        ConcertAdded::dispatch($concert);

        return redirect()->route('backstage.concerts.index');
    }

    public function edit($id)
    {
        $concert = Auth::user()->concerts()->findOrFail($id);

        abort_if($concert->isPublished(), 403);

        return view('backstage.concerts.edit', [
            'concert' => $concert,
        ]);
    }

    public function update($id)
    {
        $concert = Auth::user()->concerts()->findOrFail($id);
        abort_if($concert->isPublished(), 403);

        $this->validate(request(), [
            'title' => ['required'],
            'date' => ['required', 'date'],
            'time' => ['required', 'date_format:g:ia'],
            'venue' => ['required'],
            'venue_address' => ['required'],
            'city' => ['required'],
            'state' => ['required'],
            'zip' => ['required'],
            'ticket_price' => ['required', 'numeric', 'min:5'],
            'ticket_quantity' => ['required', 'integer', 'min:1'],
        ]);

        $concert->update([
            'title' => request('title'),
            'subtitle' => request('subtitle'),
            'additional_information' => request('additional_information'),
            'date' => Carbon::parse(vsprintf('%s %s', [
                request('date'),
                request('time'),
            ])),
            'venue' => request('venue'),
            'venue_address' => request('venue_address'),
            'city' => request('city'),
            'state' => request('state'),
            'zip' => request('zip'),
            'ticket_price' => request('ticket_price') * 100,
            'ticket_quantity' => (int) request('ticket_quantity'),
        ]);

        return redirect()->route('backstage.concerts.index');
    }
}

app/Http/Controllers/Backstage/PublishedConcertOrdersController.php
<?php

namespace App\Http\Controllers\Backstage;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PublishedConcertOrdersController extends Controller
{
    public function index($concertId)
    {
        $concert = Auth::user()->concerts()->published()->findOrFail($concertId);

        return view('backstage.published-concert-orders.index', [
            'concert' => $concert,
            'orders' => $concert->orders()->latest()->take(10)->get(),
        ]);
    }
}

app/Http/Controllers/Backstage/PublishedConcertsController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Concert;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PublishedConcertsController extends Controller
{
    public function store()
    {
        $concert = Auth::user()->concerts()->findOrFail(request('concert_id'));

        if ($concert->isPublished()) {
            abort(422);
        }

        $concert->publish();

        return redirect()->route('backstage.concerts.index');
    }
}

app/Http/Controllers/Backstage/StripeConnectController.php
<?php

namespace App\Http\Controllers\Backstage;

use Zttp\Zttp;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class StripeConnectController extends Controller
{
    public function connect()
    {
        return view('backstage.stripe-connect.connect');
    }

    public function authorizeRedirect()
    {
        $url = vsprintf('%s?%s', [
            'https://connect.stripe.com/oauth/authorize',
            http_build_query([
                'response_type' => 'code',
                'scope' => 'read_write',
                'client_id' => config('services.stripe.client_id'),
            ]),
        ]);

        return redirect($url);
    }

    public function redirect()
    {
        $accessTokenResponse = Zttp::asFormParams()->post('https://connect.stripe.com/oauth/token', [
            'grant_type' => 'authorization_code',
            'code' => request('code'),
            'client_secret' => config('services.stripe.secret'),
        ])->json();

        Auth::user()->update([
            'stripe_account_id' => $accessTokenResponse['stripe_user_id'],
            'stripe_access_token' => $accessTokenResponse['access_token'],
        ]);

        return redirect()->route('backstage.concerts.index');
    }
}

app/Http/Controllers/ConcertsController.php
<?php

namespace App\Http\Controllers;

use App\Concert;
use Illuminate\Http\Request;

class ConcertsController extends Controller
{
    public function show($id)
    {
        $concert = Concert::published()->findOrFail($id);
        return view('concerts.show', ['concert' => $concert]);
    }
}

resources/views/backstage/concerts/edit.blade.php
@extends('layouts.backstage')

@section('backstageContent')
<div class="bg-light p-xs-y-4 border-b">
    <div class="container">
        <h1 class="text-lg">Edit concert</h1>
    </div>
</div>
<form class="bg-soft p-xs-y-5" action="{{ route('backstage.concerts.update', $concert) }}" method="POST">
    {{ csrf_field() }}
    {{ method_field('PATCH') }}

    @if ($errors->any())
    <div class="container m-xs-b-4">
        <div class="alert alert-danger">
            <h2 class="text-base text-danger wt-bold m-xs-b-2">
                There {{ $errors->count() == 1 ? 'is' : 'are' }} {{ $errors->count() }} {{ str_plural('error', $errors->count() )}} with this concert:
            </h2>
            <ul class="bullet-list text-danger">
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
    @endif

    <div class="border-b p-xs-b-4 m-xs-b-4">
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div class="p-xs-y-4">
                        <h2 class="text-base wt-medium m-xs-b-4">Concert Details</h2>
                        <p class="text-dark-soft text-sm m-xs-b-4">Tell us who's playing! <em>(Please be Slayer!)</em></p>
                        <p class="text-dark-soft text-sm">Include the headliner in the concert name, use the subtitle section to list any opening bands, and add any important information to the description.</p>
                    </div>
                </div>
                <div class="col col-lg-8">
                    <div class="card">
                        <div class="card-section">
                            <div class="form-group {{ $errors->first('title', 'has-error') }}">
                                <label class="form-label">Title</label>
                                <input name="title" class="form-control" value="{{ old('title', $concert->title) }}" placeholder="The Headliners">
                            </div>
                            <div class="form-group {{ $errors->first('subtitle', 'has-error') }}">
                                <label class="form-label">Subtitle</label>
                                <input name="subtitle" class="form-control" value="{{ old('subtitle', $concert->subtitle) }}" placeholder="with The Openers (optional)">
                            </div>
                            <div class="form-group {{ $errors->first('additional_information', 'has-error') }}">
                                <label class="form-label">Additional Information</label>
                                <textarea name="additional_information" class="form-control" rows="4" placeholder="This concert is 19+ (optional)">{{ old('additional_information', $concert->additional_information) }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="border-b p-xs-b-4 m-xs-b-4">
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div class="p-xs-y-4">
                        <h2 class="text-base wt-medium m-xs-b-4">Date &amp; Time</h2>
                        <p class="text-dark-soft text-sm">True metalheads really only care about the obscure openers, so make sure they don't get there late!</p>
                    </div>
                </div>
                <div class="col col-lg-8">
                    <div class="card">
                        <div class="card-section">
                            <div class="row">
                                <div class="col col-md-6">
                                    <div class="form-group {{ $errors->first('date', 'has-error') }}">
                                        <label class="form-label">Date</label>
                                        <input type="date" name="date" class="form-control" placeholder="yyyy-mm-dd" value="{{ old('date', $concert->date->format('Y-m-d')) }}">
                                    </div>
                                </div>
                                <div class="col col-md-6">

                                    <div class="form-group {{ $errors->first('time', 'has-error') }}">
                                        <label class="form-label">Start Time</label>
                                        <input  name="time" class="form-control" placeholder="7:00pm" value="{{ old('time', $concert->date->format('g:ia')) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="border-b p-xs-b-4 m-xs-b-4">
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div class="p-xs-y-4">
                        <h2 class="text-base wt-medium m-xs-b-4">Venue Information</h2>
                        <p class="text-dark-soft text-sm">Where's the show? Let attendees know the venue name and address so they can bring the mosh.</p>
                    </div>
                </div>
                <div class="col col-lg-8">
                    <div class="card">
                        <div class="card-section">
                            <div class="form-group {{ $errors->first('venue', 'has-error') }}">
                                <label class="form-label">Venue Name</label>
                                <input name="venue" class="form-control" value="{{ old('venue', $concert->venue) }}" placeholder="The Mosh Pit">
                            </div>
                            <div class="form-group {{ $errors->first('venue_address', 'has-error') }}">
                                <label class="form-label">Stree Address</label>
                                <input name="venue_address" class="form-control" value="{{ old('venue_address', $concert->venue_address) }}" placeholder="500 Example Ave.">
                            </div>
                            <div class="row">
                                <div class="col col-sm-4">
                                    <div class="form-group {{ $errors->first('city', 'has-error') }}">
                                        <label class="form-label">City</label>
                                        <input name="city" class="form-control" value="{{ old('city', $concert->city) }}" placeholder="Laraville">
                                    </div>
                                </div>
                                <div class="col col-sm-4">
                                    <div class="form-group {{ $errors->first('state', 'has-error') }}">
                                        <label class="form-label">State/Province</label>
                                        <input name="state" class="form-control" value="{{ old('state', $concert->state) }}" placeholder="ON">
                                    </div>
                                </div>
                                <div class="col col-sm-4">
                                    <div class="form-group {{ $errors->first('zip', 'has-error') }}">
                                        <label class="form-label">ZIP</label>
                                        <input name="zip" class="form-control" value="{{ old('zip', $concert->zip) }}" placeholder="90210">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="border-b p-xs-b-4 m-xs-b-4">
        <div class="container">
            <div class="row">
                <div class="col col-lg-4">
                    <div class="p-xs-y-4">
                        <h2 class="text-base wt-medium m-xs-b-4">Tickets &amp; Pricing</h2>
                        <p class="text-dark-soft text-sm">Set your ticket price and availability, but don't forget, metalheads are cheap so keep it reasonable.</p>
                    </div>
                </div>
                <div class="col col-lg-8">
                    <div class="card">
                        <div class="card-section">
                            <div class="row">
                                <div class="col col-md-6">
                                    <div class="form-group {{ $errors->first('ticket_price', 'has-error') }}">
                                        <label class="form-label">Price</label>
                                        <div class="input-group">
                                            <span class="input-group-addon text-dark-muted">
                                                $
                                            </span>
                                            <input name="ticket_price" class="form-control" placeholder="0.00" value="{{ old('ticket_price', $concert->ticket_price_in_dollars) }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col col-md-6">
                                    <div class="form-group {{ $errors->first('ticket_quantity', 'has-error') }}">
                                        <label class="form-label">Ticket Quantity</label>
                                        <input name="ticket_quantity" class="form-control" placeholder="250" value="{{ old('ticket_quantity', $concert->ticket_quantity) }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container text-right">
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </div>
</form>
@endsection

resources/views/backstage/concerts/index.blade.php
@extends('layouts.backstage')

@section('backstageContent')
<div class="bg-light p-xs-y-4 border-b">
    <div class="container">
        <div class="flex-spaced flex-y-center">
            <h1 class="text-lg">Your concerts</h1>
            <a href="{{ route('backstage.concerts.new') }}" class="btn btn-primary">Add concert</a>
        </div>
    </div>
</div>
<div class="bg-soft p-xs-y-5">
    <div class="container m-xs-b-4">
        <div class="m-xs-b-6">
            <h2 class="m-xs-b-3 text-base wt-medium text-dark-soft">Published</h2>
            <div class="row">
                @foreach ($publishedConcerts as $concert)
                <div class="col-xs-12 col-lg-4">
                    <div class="card m-xs-b-4">
                        <div class="card-section">
                            <div class="m-xs-b-4">
                                <div class="m-xs-b-2">
                                    <h1 class="text-lg wt-bold">{{ $concert->title }}</h1>
                                    <p class="wt-medium text-dark-soft text-ellipsis">{{ $concert->subtitle }}</p>
                                </div>
                                <p class="text-sm m-xs-b-2">
                                    @icon('location', 'zondicon-sm text-dark-soft m-xs-r-1')
                                    {{ $concert->venue }} &ndash; {{ $concert->city }}, {{ $concert->state }}
                                </p>
                                <p class="text-sm">
                                    @icon('calendar', 'zondicon-sm text-dark-soft m-xs-r-1')
                                    {{ $concert->formatted_date }} @ {{ $concert->formatted_start_time }}
                                </p>
                            </div>
                            <div>
                                <a href="{{ route('backstage.published-concert-orders.index', $concert) }}" class="btn btn-sm btn-secondary m-xs-r-2">Manage</a>
                                <a href="{{ route('concerts.show', $concert) }}" class="link-brand text-sm wt-medium">Public Link</a>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        <div>
            <h2 class="m-xs-b-3 text-base wt-medium text-dark-soft">Drafts</h2>
            <div class="row">
                @foreach ($unpublishedConcerts as $concert)
                <div class="col-xs-12 col-lg-4">
                    <div class="card m-xs-b-4">
                        <div class="card-section">
                            <div class="m-xs-b-4">
                                <div class="m-xs-b-2">
                                    <h1 class="text-lg wt-bold">{{ $concert->title }}</h1>
                                    <p class="wt-medium text-dark-soft text-ellipsis">{{ $concert->subtitle }}</p>
                                </div>
                                <p class="text-sm m-xs-b-2">
                                    @icon('location', 'zondicon-sm text-dark-soft m-xs-r-1')
                                    {{ $concert->venue }} &ndash; {{ $concert->city }}, {{ $concert->state }}
                                </p>
                                <p class="text-sm">
                                    @icon('calendar', 'zondicon-sm text-dark-soft m-xs-r-1')
                                    {{ $concert->formatted_date }} @ {{ $concert->formatted_start_time }}
                                </p>
                            </div>
                            <div>
                                <a href="{{ route('backstage.concerts.edit', $concert) }}" class="btn btn-sm btn-secondary m-xs-r-2">Edit</a>
                                <form class="inline-block" action="{{ route('backstage.published-concerts.store') }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="concert_id" value="{{ $concert->id }}">
                                    <button type="submit" class="btn btn-sm btn-primary">Publish</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</div>
@endsection